### PR TITLE
Add Safe wallet

### PR DESCRIPTION
**Pull request by marcuspang**

### CODE REVIEW

**Review by mrTomatolegit — CHANGES_REQUESTED** [review]
It doesn't build. Typescript build errors, check files attached...
Also lint your code

[yarn build.log](https://github.com/RadarDAO-xyz/radar-launch/files/12067522/yarn.build.log)
[yarn preview.log](https://github.com/RadarDAO-xyz/radar-launch/files/12067536/yarn.preview.log)

**Comment by marcuspang** [comment]
@mrTomatolegit yes, I wasnt planning on merging it so soon

**Comment by mrTomatolegit** [comment]
> @mrTomatolegit yes, I wasnt planning on merging it so soon

Misunderstood the open pull request that was opened so soon

50360794f3348165616e9c782fbf2ffe55e6a4cc:
Why did you commit the built files in?

**Comment by marcuspang** [comment]
> > @mrTomatolegit yes, I wasnt planning on merging it so soon
> 
> Misunderstood the open pull request that was opened so soon
> 
> [5036079](https://github.com/RadarDAO-xyz/radar-launch/commit/50360794f3348165616e9c782fbf2ffe55e6a4cc): Why did you commit the built files in?

Hmm my cached files didnt get deleted, was going to compile them initially to import in webflow

**Comment by mrTomatolegit** [comment]
Closing this since it's moved to https://github.com/RadarDAO-xyz/radar-launch-frontend

**Pull request closed without merging**
